### ISSUE TITLE
track.imageUrl is always null

### ISSUE THREAD

**Issue by lucavinci** [brim-borium/spotify_sdk#10]
Currently, there is no functioning way to get the image url of the album art of the currently playing track.
`playerState.track.imageUri` is always null.

This is very important because now, I have to use the spotify web api to fetch the track with the `track.uri` just to get the image uri.

**Comment by brim-borium** [comment]
Currently this feature is not implemented on the platform side. I will have a look at this and see if I can implement it this week

**Comment by lucavinci** [comment]
Sorry, I read over that. Thank you for your quick reply :)

**Comment by eddwhite** [comment]
I've fixed the issue and created a PR 😄 It was an issue with JSON keys. 
I discovered it when I wasn't able to get track duration (same issue, also fixed).

**Comment by brim-borium** [comment]
Thanks to eddwhite, this is now done for android and already pushed to develop. I will push a new version to pub.dev this evening.

**Comment by lucavinci** [comment]
Thanks so much @brim-borium and @eddwhite for your work!!!

**Comment by brim-borium** [comment]
New version has been published
