### ISSUE TITLE
2.1.0 won't build for Android

### ISSUE THREAD

**Issue by mcookhome** [brim-borium/spotify_sdk#101]
**Describe the bug**
I am not able to build my app on Android when moving from version 1.0.0 to 2.1.0.

**To Reproduce**

Use ^2.1.0 as version for spotify_sdk in pubspec.yaml, build app.

**Expected behavior**
I expect the build to pass.

**Error message**

Here's the error message I get, which is coming from this package:
```

:spotify_sdk:processDebugManifest FAILED 

/Users/mcook/personal/flutter/.pub-cache/hosted/pub.dartlang.org/spotify_sdk-2.1.0/android/src/main/AndroidManifest.xml:9:9-53 Error:
	Missing 'package' key attribute on element package at AndroidManifest.xml:9:9-53
/Users/mcook/personal/flutter/.pub-cache/hosted/pub.dartlang.org/spotify_sdk-2.1.0/android/src/main/AndroidManifest.xml Error:
	Validation failed, exiting

```

I cannot use this newest version on Android phones for this reason.

**Comment by mcookhome** [comment]
It seems like it's coming from [this line of code](https://github.com/brim-borium/spotify_sdk/blob/35a7815b0d90dd9418219d3a777de5d3737dc301/android/src/main/AndroidManifest.xml#L9).

That line was introduced by [this commit](https://github.com/brim-borium/spotify_sdk/pull/76/files#diff-93083d0574bec8be4b25f798b65dd82a612412c23a79dc9bdfdfb4a6b7ab37a3R9).

I don't think I'm doing anything wrong from my side, but please let me know if there's anything I can add that may be helpful to diagnose this issue.

**Comment by mcookhome** [comment]
@fotiDim, if I understand correctly, you work on the iOS part of this project, but do you mind helping put me in contact with someone to discuss this issue with? I may be doing something wrong, but I'd really like to be able to upgrade to 2.1.0 so I can use the improvements you added to the library in that version 😄 .

Any help would be greatly appreciated! thanks

**Comment by brim-borium** [comment]
Hi @mcookhome I will have a look at this sometime tomorrow in the evening :) 

Quick question, are you using Android studio or Vs code for development and which version are you using?

**Comment by mcookhome** [comment]
Hey @brim-borium, thanks so much for taking a look!

I'm using Android Studio for development - here's the `About Android Studio` details:

![image](https://user-images.githubusercontent.com/5422547/120073124-0ac75e80-c065-11eb-8bc3-b52a7a23ffef.png)

Please let me know if there's any more information I can provide, or if I need to update, or anything. Thanks!

**Comment by brim-borium** [comment]
So after further investigating I figured out why this line was added: 
https://community.spotify.com/t5/Spotify-for-Developers/Why-can-t-I-use-the-SDK-on-Android-OS-11/td-p/5061178

We need this to be able to build on Android 11. @mcookhome which android version are you using?

**Comment by mcookhome** [comment]
Hi, thanks for the update!!! My device is on Android 11.

> Also I found this, so it seem that the gradle version needs to be up to date too mattermoran/map_launcher#60 (comment), could be something you need to look into

This worked for me and solved the problem!

I changed this line:
```
        classpath 'com.android.tools.build:gradle:3.5.0'
```

to be 

```
        classpath 'com.android.tools.build:gradle:3.5.4'

```

in my build.gradle file, and the build worked just fine! thanks so much for your help!

**Comment by brim-borium** [comment]
@mcookhome glad I could help :)
