### ISSUE TITLE
App getting IllegalStateException. In Idle mode the app takes a shutdown due to Exception

### ISSUE THREAD

**Issue by dagnorland** [brim-borium/spotify_sdk#11]
• open_sdk 3.2 
    • Flutter version 1.12.13+hotfix.8 at c:\dev\flutter
    • Framework revision 0b8abb4724 (3 weeks ago), 2020-02-11 11:44:36 -0800
    • Engine revision e1e6ced81d
    • Dart version 2.7.0

E/AndroidRuntime(11546): Process: no.emsp.dj_sportshall, PID: 11546
E/AndroidRuntime(11546): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(11546): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:148)
E/AndroidRuntime(11546): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler$1.error(MethodChannel.java:239)
E/AndroidRuntime(11546): 	at de.minimalme.spotify_sdk.SpotifySdkPlugin$connectToSpotify$1.onFailure(SpotifySdkPlugin.kt:172)
E/AndroidRuntime(11546): 	at com.spotify.android.appremote.api.LocalConnector$1.lambda$onConnected$0(LocalConnector.java:88)
E/AndroidRuntime(11546): 	at com.spotify.android.appremote.api.-$$Lambda$LocalConnector$1$IbZLttZmA0yUOwLQJq9O0FFxzoA.onConnectionTerminated(Unknown Source:4)
E/AndroidRuntime(11546): 	at com.spotify.protocol.client.RemoteWampClient$1.onGoodbye(RemoteWampClient.java:52)
E/AndroidRuntime(11546): 	at com.spotify.protocol.client.WampRouterImpl.routeGoodbye(WampRouterImpl.java:107)
E/AndroidRuntime(11546): 	at com.spotify.protocol.client.WampRouterImpl.route(WampRouterImpl.java:30)
E/AndroidRuntime(11546): 	at com.spotify.protocol.client.AppProtocolCommunicator.onData(AppProtocolCommunicator.java:78)
E/AndroidRuntime(11546): 	at com.spotify.android.appremote.internal.RemoteServiceIo.handleMessage(RemoteServiceIo.java:113)
E/AndroidRuntime(11546): 	at com.spotify.android.appremote.internal.RemoteServiceIo.access$000(RemoteServiceIo.java:47)
E/AndroidRuntime(11546): 	at com.spotify.android.appremote.internal.RemoteServiceIo$IncomingHandler.handleMessage(RemoteServiceIo.java:91)
E/AndroidRuntime(11546): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(11546): 	at android.os.Looper.loop(Looper.java:193)
E/AndroidRuntime(11546): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/AndroidRuntime(11546): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11546): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/AndroidRuntime(11546): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/Process (11546): Sending signal. PID: 11546 SIG: 9

**Comment by dagnorland** [comment]
Priori to this exception I have several : 
W/p.dj_sportshal(13617): Unable to resolve Lcom/spotify/protocol/types/Message; annotation class 6
W/p.dj_sportshal(13617): Unable to resolve Lcom/spotify/protocol/types/Message; annotation class 7
W/p.dj_sportshal(13617): Unable to resolve Lcom/spotify/protocol/types/Message; annotation class 7
D/AndroidRuntime(13617): Shutting down VM
E/AndroidRuntime(13617): FATAL EXCEPTION: main
E/AndroidRuntime(13617): Process: no.emsp.dj_sportshall, PID: 13617
E/AndroidRuntime(13617): java.lang.IllegalStateException: Reply already submitted
E/AndroidRuntime(13617): 	at io.flutter.embedding.engine.dart.DartMessenger$Reply.reply(DartMessenger.java:148)

**Comment by brim-borium** [comment]
Will have a look at this on the weekend

**Comment by lucavinci** [comment]
I am always getting these every 10-15 minutes in debug mode, but when I release the app it works perfectly and it never crashes.

**Comment by dagnorland** [comment]
> I am always getting these every 10-15 minutes in debug mode, but when I release the app it works perfectly and it never crashes.

I even have it on my tablet after I have installed the app as an --release apk build.

**Comment by itsMatoosh** [comment]
This issue happens because the plugin doesn't handle unexpected disconnects from Spotify properly. The plugin will crash whenever the onFailure callback of the Spotify connect method is called more than once.
https://github.com/brim-borium/spotify_sdk/blob/492748a1c90f0fbfa3f6da2e1619d4506463623e/android/src/main/kotlin/de/minimalme/spotify_sdk/SpotifySdkPlugin.kt#L160-L174

The onFailure here can run after the Spotify connection has already been established, which will then cause a plugin crash. To fix this, instead of using it as the result of the connect method, the onFailure should raise a special event that will notify the plugin that the Spotify connection was terminated.

**Comment by lucavinci** [comment]
> This issue happens because the plugin doesn't handle unexpected disconnects from Spotify properly. The plugin will crash whenever the onFailure callback of the Spotify connect method is called more than once.
> https://github.com/brim-borium/spotify_sdk/blob/492748a1c90f0fbfa3f6da2e1619d4506463623e/android/src/main/kotlin/de/minimalme/spotify_sdk/SpotifySdkPlugin.kt#L160-L174
> 
> The onFailure here can run after the Spotify connection has already been established, which will then cause a plugin crash. To fix this, instead of using it as the result of the connect method, the onFailure should raise a special event that will notify the plugin that the Spotify connection was terminated.

This seems to be a great fix. Introducing an onFailure event will let the users of the package display a custom error message.

**Comment by brim-borium** [comment]
Started working on this. You can have a look at my initial thoughts on handling this. Not quite sure yet what's the best way to talk back to the flutter plugin

**Comment by itsMatoosh** [comment]
@brim-borium I made some changes to your implementation of unexpected disconnection handling. It adds a connection state event that will notify users of the current Spotify connection status and any errors that occur. Please take a look at my PR.

**Comment by brim-borium** [comment]
@itsMatoosh I merged the changes into the feature branch, will probably test this this weekend, but this looks promising :) thanks!

**Comment by brim-borium** [comment]
This should be fixed in the new version 0.3.4
