### ISSUE TITLE
Support the Spotify Web API 

### ISSUE THREAD

**Issue by Tom3652** [brim-borium/spotify_sdk#111]
**Feature :**

I simply would like to fetch songs / artists from Spotify in my Android / IOS app as it is possible using the Web API with HTTP requests.

**Solution :**

This would not require to open the Spotify application or anything, simply by providing credentials to log in the developper account on the client side. 
We are not fetching a specific user content, but the Spotify general content instead such as public playlists / artists etc...
My goal is to provide a "popular" music list like Instagram to add on a specific video / photo and i believe that this can be made through the Spotify Web API.

**Comment by fotiDim** [comment]
You might be looking into the wrong project. The purpose of this library is not to expose Spotify's web API but to provide Flutter bindings for the native Spotify SDKs. We can only provide whatever the native SDKs provide.

**Comment by Tom3652** [comment]
Thanks for your reply, i am going to close this as it is out of scope then
