### ISSUE TITLE
On Web the SDKs always open the Spotify consent popup

### ISSUE THREAD

**Issue by nzoschke** [brim-borium/spotify_sdk#112]
**Describe the bug**

It doesn't seem possible to initialize the SDK with a good token without sending the user to the Spotify consent popup.

On the web platform, both getAuthenticationToken and connectToSpotifyRemote always open the consent popup.

In experiments with the Spotify web playback SDK and API client in other web projects, it's possible to avoid the consent popup as long as I have a valid token ahead of time.

**To Reproduce**
1. Request a token with getAuthenticationToken. The SDK always shows the Spotify consent popup
2. Optionally get an access / refresh token with a server-side OAuth flow. The `show_dialog` parameter makes it possible to perform this flow without showing the consent popup after the first successful flow.
2. Pass a token to connectToSpotifyRemote. The SDK always shows the Spotify consent popup

**Expected behavior**

The docs state that:

> On iOS you can store the token that you get from getAuthenticationToken(...) and then pass it to connectToSpotifyRemote(...) during the next session. This will avoid having to switch to the Spotify app for establishing the connection.

I have the same expectation for the web SDK in general, and from using it directly in other web apps, that it should be possible to `connectToSpotifyRemote` without prompting for auth as long as I have a valid token.

However when getting a token with getAuthenticationToken, it always opens the Spotify consent popup. Then when passing this token to connectToSpotifyRemote it always opens the Spotify consent popup again.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: web
 - Browser: Chrome
 - Version: 91.0.4472.77 (Official Build) (x86_64)

**Additional context**

I suspect there are assumptions in how the library generates the spotify auth URLs. 

The [authorization guide doc](https://developer.spotify.com/documentation/general/guides/authorization-guide/) documents a `show_dialog` option which may need to be set to false.

I also see that the library is always doing the PKCE flow, which may break the flow from a full server-side Authorization Code flow.

I'll dig into the library more and see what I can find.

**Comment by nzoschke** [comment]
In `spotify_sdk_web.dart`, connectToSpotify is always calling `await _authorizeSpotify` which opens the auth window. I am investigating a patch to pass an existing token to the SDK to avoid this.

**Comment by fotiDim** [comment]
@nzoschke is this still an issue or was it covered with your PR?

**Comment by nzoschke** [comment]
This is now addressed with my PRs. Thanks!
