### ISSUE TITLE
How can I get the current playing track's duration counter?

### ISSUE THREAD

**Issue by irfan-429** [brim-borium/spotify_sdk#120]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by brim-borium** [comment]
Hi @irfan-429 just to clarify to you mean the current playbacktime?

**Comment by irfan-429** [comment]
Yes exactly!!

**Comment by fotiDim** [comment]
`getPlayerState()` or `subscribeToPlayerState()` is the way to go. The `PlayerState` object has a `playbackPosition` property.
