### ISSUE TITLE
Cann't play selected track with SpotifySdk.play()

### ISSUE THREAD

**Issue by Rayyanmaq1** [brim-borium/spotify_sdk#126]
**Describe the bug*
I am using Spotify package for Searching song through title and Spotify_sdk package for authentication and play song but I am unable to play the selected song I am passing the spotifyuri of the selected track but i play some different song mostly.

Here are the packages that i am using
1. Go to 'https://pub.dev/packages/spotify_sdk'
2. Go to 'https://pub.dev/packages/spotify'

**Screenshots**
<img width="871" alt="Screenshot 2021-07-28 at 12 08 52 PM" src="https://user-images.githubusercontent.com/71687063/127314561-3a04f288-7366-4f9b-8b21-ef7ad017008d.png">
<img width="445" alt="Screenshot 2021-07-28 at 12 09 07 PM" src="https://user-images.githubusercontent.com/71687063/127314571-3976509f-a434-4c6d-a583-b4755b801c71.png">

**Comment by AlexFox63** [comment]
Your spotify account need a premium subscription for playing selected track else spotify playing random track
