### ISSUE TITLE
There is a pause in the playback. 

### ISSUE THREAD

**Issue by irfan-429** [brim-borium/spotify_sdk#127]
When I play any track for the first time from my List of songs, it takes a pause around 4-7 seconds and then plays the song.

**Comment by fotiDim** [comment]
It seems a bit unlikely that this is a problem with this package. Are you still facing the issue?

**Comment by irfan-429** [comment]
It only happens with Free version of Spotify. Using paid version it works like a charm. It's from Spotify.
