### ISSUE TITLE
No connection can be established with the player.

### ISSUE THREAD

**Issue by Ruud14** [brim-borium/spotify_sdk#141]
Hi, I am working on a flutter project and I want to use the Spotify Api on Anroid, IOS and web.
This package seems perfect for what I need.
However, the [example](https://github.com/brim-borium/spotify_sdk/tree/main/example) doesn't seem to work.
I created an app in the spotify developer dashboard, added the android package name and added the redirect url.

However the example app can't get the player state etc, even though the spotify app is installed and open in the background.
Getting the auth token works fine though.

I've tried this on an Android 8.1 emulator and on my real Phone running Android 11.

The Spotify_sdk version is 2.1.0.

Is there something that I am doing wrong or is the example not working?

**Comment by alanhmartins** [comment]
The same thing happens to me. Managed to solve?

**Comment by Ruud14** [comment]
I couldn't get it working on my desktop, so I tried it on my laptop and there it did work. At first I was really confused, but the issue turned out to be that the fingerprint that I was using on my desktop wasn't working so it worked after creating a new fingerprint and adding that to the spotify dashboard.
