### ISSUE TITLE
 Works on debug but not on release

### ISSUE THREAD

**Issue by alanhmartins** [brim-borium/spotify_sdk#142]
Hi guys very nice. It's working 100% in the debug, but when I generate the release version it doesn't return the music, the image, and the playlist data for example, does anyone have a light?

**Comment by fotiDim** [comment]
Please use the issue template when opening new issues.

**Comment by irfan-429** [comment]
Did you try adding *release SHA1 fingerprint* in Spotify Dashboard?

**Comment by EXEIdeas** [comment]
I also have the same problem now in iOS. It worked earlier in many releases but now it is not working in TestFlight either. Any suggestions?
