### ISSUE TITLE
[iOS] Spotify_sdk player's requests NEVER come back with their callbacks.

### ISSUE THREAD

**Issue by irfan-429** [brim-borium/spotify_sdk#150]
**Is this a native Spotify SDK issue**
No

**Are you using a Free or Premium Spotify account**
Premium

**Expected behavior**
Spotify_sdk must respond with a callback when I perform actions like play/pause/getPlayerState on a song.  

**Describe the bug**
Pre-issue:
I was facing an [issue like this](https://github.com/brim-borium/spotify_sdk/issues/68) and I try to solve his way but it didn't solve. I also tried with [this way around](https://github.com/brim-borium/spotify_sdk/issues/86) where I added a wrong `spotifyUri` while connecting using `SpotifySdk.connectToSpotifyRemote()` and it worked!! i.e., Spotify app didn't played song automatically after adding wrong spotifyUri. 

Actual/current issue:
When I perform actions like play/pause/getPlayerState on a song, my requests go but they NEVER come back with their callbacks after few successful requests. Rather my all queued requests respond back suddenly when I switch from the app to Spotify App. See the screen shot below:

**Steps to Reproduce**
1. Followed [iOS quick start](https://developer.spotify.com/documentation/ios/quick-start/) documentation
2. Connect to Spotify remote with/without `accessToken` but with a wrong `spotifyUri` as a param
3. Play and keep playing different songs one by one 
4. After few successful attempts, you won't be able to perform further actions on a song

**Screenshots**
[logs screenshot](https://drive.google.com/file/d/1DBQX7X2m01a1BIGqiKt2oYkCFhsS4dr9/view?usp=sharing), 
[Project dir structure](https://drive.google.com/file/d/1TyuWdA5JUAtkhWRMHv-vq--TetirVS41/view?usp=sharing),
[Xcode dir structure](https://drive.google.com/file/d/1Ihxbeigw3NYn9qTrKWy_BFAVHhbRM2xO/view?usp=sharing)

**Spotify_sdk Flutter package version**
`spotify_sdk: ^2.2.0`

**Target Platform, Version & Device**
 - OS & Version: [iOS 15.2]
 - Device: [iPhone 11 Pro]
 
**Development OS**
 - OS: [Mac OS]

**Comment by irfan-429** [comment]
@fotiDim - Can you please checkout my query? It'd be much helpful to meet my deadline.

**Comment by fotiDim** [comment]
@irfan-429 some clarifications needed:
- Does the issue also happen when you pass a `valid` spotifyUri?
- Does the issue also happen when you don't pass any spotifyUri?
- "After few successful attempts, you won't be able to perform further actions on a song" Does that literally mean that you cannot perform any action (eg. pause) or just that you are not getting back the callback?

**Comment by fotiDim** [comment]
Closing due to lack of feedback. If the issue persists please report back.
