### ISSUE TITLE
Can this package get converted to native dart

### ISSUE THREAD

**Issue by guyluz11** [brim-borium/spotify_sdk#151]
I was wondering if this package or part of it can get converted to native dart and thus work on all platforms, and can get executed from server side as well?.

What part of this library require the flutter framework and what part of it only required native dart code.

**Comment by fotiDim** [comment]
Nope, not possible with this package. The dart part is essentially glue code calling native APIs.

**Comment by guyluz11** [comment]
I see, thanks.
