### ISSUE TITLE
Authentication token: wording issue?

### ISSUE THREAD

**Issue by wackazong** [brim-borium/spotify_sdk#152]
In the documentation and code you are using the term "Authentication Token". Could it be that this should better be called an "Access Token" in order to comply with OAuth terminology? I think you are actually referring to the access token. Since there is also the authorization code in the OAuth flow, the term "Authentication Token" is confusing IMHO.

**Comment by fotiDim** [comment]
Fair point. I will improve this along with a dead link that I found in the readme.
