### ISSUE TITLE
Spotify changed the redirect URL callback to #access_token and now the athentication is failling

### ISSUE THREAD

**Issue by vikrantyadav7** [brim-borium/spotify_sdk#158]
**Is this a how to question?**
No

**Is this a native Spotify SDK issue**
No

**Are you using a Free or Premium Spotify account**
Premium

**Are you aware of the limitation of Free Spotify accounts**
Yes

**Describe the bug**
The getAthenticationToken function is not working . And i think the thats because Spotify has changed its redirect url . when i call the url generated by this function it returns the access token in the URL but its been changed to #access_token instead of #accessToken

**Spotify_sdk Flutter package version**
spotify_sdk: ^2.2.0

**Target Platform, Version & Device**
 - Device: Realme 3 pro 
 
**Development OS**
 - OS:  Windows

**Comment by brim-borium** [comment]
![image](https://user-images.githubusercontent.com/4504079/151837310-0f93968c-c5fc-4cec-8cb5-cdd7ba52851f.png)

tested with the current develop and the following parameters and i got a working token back

**Comment by vikrantyadav7** [comment]
but in my case i giving me an error and i didnt changed anything . my client id and redirect url is the same . and when i click on the link generated by the fucntion i get the token in the redirect url .

[https://accounts.spotify.com/en/authorize?client_id=bbc2d117bece48ebaa067a59dc8885f9&response_type=token&redirect_uri=https:%2F%2Fgroove-338604.wn.r.appspot.com%2Fapp%2Fv1%2FspotifyCallback&show_dialog=false&utm_source=spotify-sdk&utm_medium=android-sdk&utm_campaign=android-sdk&scope=app-remote-control%20%20user-modify-playback-state%20%20playlist-read-private%20%20user-read-email%20%20user-read-private%20%20user-follow-modify%20%20user-follow-read%20%20user-library-modify%20%20user-library-read%20%20user-top-read%20%20user-read-playback-state%20user-read-recently-played%20%20playlist-read-collaborative%20%20playlist-modify-private%20%20playlist-modify-public%20%20user-read-currently-playing)](https://accounts.spotify.com/en/authorize?client_id=bbc2d117bece48ebaa067a59dc8885f9&response_type=token&redirect_uri=https:%2F%2Fgroove-338604.wn.r.appspot.com%2Fapp%2Fv1%2FspotifyCallback&show_dialog=false&utm_source=spotify-sdk&utm_medium=android-sdk&utm_campaign=android-sdk&scope=app-remote-control%20%20user-modify-playback-state%20%20playlist-read-private%20%20user-read-email%20%20user-read-private%20%20user-follow-modify%20%20user-follow-read%20%20user-library-modify%20%20user-library-read%20%20user-top-read%20%20user-read-playback-state%20user-read-recently-played%20%20playlist-read-collaborative%20%20playlist-modify-private%20%20playlist-modify-public%20%20user-read-currently-playing]

**Comment by brim-borium** [comment]
Which function does generate this link for you?

**Comment by vikrantyadav7** [comment]
yes

**Comment by vikrantyadav7** [comment]
THIS IS MY CONSOLE WHEN I CALL THE FUNCTION.
<D/com.spotify.sdk.android.auth.LoginActivity(30826): Spotify Auth starting with the request [https://accounts.spotify.com/authorize?client_id=bbc2d117bece48ebaa067a59dc8885f9&response_type=token&redirect_uri=https%3A%2F%2Fgroove-338604.wn.r.appspot.com%2Fapp%2Fv1%2FspotifyCallback&show_dialog=false&utm_source=spotify-sdk&utm_medium=android-sdk&utm_campaign=android-sdk&scope=app-remote-control%20%20user-modify-playback-state%20%20playlist-read-private%20%20user-read-email%20%20user-read-private%20%20user-follow-modify%20%20user-follow-read%20%20user-library-modify%20%20user-library-read%20%20user-top-read%20%20user-read-playback-state%20user-read-recently-played%20%20playlist-read-collaborative%20%20playlist-modify-private%20%20playlist-modify-public%20%20user-read-currently-playing]
E/Parcel  (30826): Reading a NULL string not supported here.
D/ColorViewRootUtil(30826): initSwipState, isDisplayCompatApp false
D/ColorViewRootUtil(30826): mScreenHeight 2340, mScreenWidth 1080
D/WindowManager(30826): Add to mViews: DecorView@921d52f[LoginActivity],pkg= com.example.music_app
V/OplusZoomWindowDecorViewHelper(30826): setLastReportedMergedConfiguration mZoomDisplayHeight: 2340 getDecorView.DecorView@921d52f[LoginActivity]
E/Parcel  (30826): Reading a NULL string not supported here.
I/com.spotify.sdk.android.auth.LoginActivity(30826): Spotify auth completing. The response is in EXTRA with key 'response'
I/flutter (30826): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (30826): │ #0   SpotifySdk._logException (package:spotify_sdk/spotify_sdk.dart:618:15)
I/flutter (30826): │ #1   SpotifySdk.getAuthenticationToken (package:spotify_sdk/spotify_sdk.dart:128:7)
I/flutter (30826): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (30826): │ ⛔ getAuthenticationToken failed with: Authentication went wrong
I/flutter (30826): │ ⛔ AUTHENTICATION_SERVICE_UNAVAILABLE
I/flutter (30826): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (30826): ┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
I/flutter (30826): │ #0   _LoginScreenState.setStatus (package:music_app/loginScreen.dart:165:13)
I/flutter (30826): │ #1   _LoginScreenState.getAuthenticationToken (package:music_app/loginScreen.dart:206:7)
I/flutter (30826): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (30826): │ 12:20:14.197 (+0:00:18.120086)
I/flutter (30826): ├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
I/flutter (30826): │ 💡 authenticationTokenErrorAuthentication went wrong
I/flutter (30826): └───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
E/flutter (30826): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: PlatformException(authenticationTokenError, Authentication went wrong, AUTHENTICATION_SERVICE_UNAVAILABLE, null).code: PlatformException(authenticationTokenError, Authentication went wrong, AUTHENTICATION_SERVICE_UNAVAILABLE, null).message>
