### ISSUE TITLE
There are two RepeatMode enums

### ISSUE THREAD

**Issue by nt4f04uNd** [brim-borium/spotify_sdk#161]
I found it confusing that there are two different RepeateMode enums. It seems like an oversight.

[First](https://github.com/brim-borium/spotify_sdk/blob/f039d9bda850ba551f34d58d7a0e4ef454701340/lib/models/player_options.dart#L23)

[Second](https://github.com/brim-borium/spotify_sdk/blob/f039d9bda850ba551f34d58d7a0e4ef454701340/lib/enums/repeat_mode_enum.dart#L2)

**Comment by brim-borium** [comment]
The one is for the user of the package to be used. The other one is for serializing and desirializing. As a user of the package I will only have access to the second enum you mentioned. Closing this.
