### ISSUE TITLE
Identify Spotify user

### ISSUE THREAD

**Issue by volgin** [brim-borium/spotify_sdk#170]
I need to store information about a user after connecting to Spotify. Oauth providers (Google. Facebook, etc.) supply some form of unique user ID, which we can store in the database. It appears that Spotify only has user's email address as a form of identification. If that's the case, it will be great if you add getUserEmail() method when access token includes user_read_email scope.

**Comment by fotiDim** [comment]
@volgin which platform are you targeting?

**Comment by volgin** [comment]
Initially iOs and Android, but later may add web and/or WIndows/MacOs.

**Comment by volgin** [comment]
Actually, Spotify does have a user ID:
https://developer.spotify.com/documentation/web-api/reference/#/operations/get-current-users-profile

This requires [user-read-private] scope. Either call works for my purposes as both IDs and emails are unique identifiers.

**Comment by fotiDim** [comment]
@volgin this plugin only supports iOS/Android/Web. Not sure how you plan to support desktop platforms.
Regarding your request, I can only speak about iOS. There is a (long) way to get the user's email through the native iOS SDK but it is not supported in this plugin for reason's of consistency and simplicity. What I suggest instead is to add the scope and then use Spotify's web API to get the email address of the user. There is the [Spotify](https://developer.spotify.com/documentation/web-api/) package that can help you with this. It should be simple enough to do.

**Comment by volgin** [comment]
I need functionality that the spofity package does not support yet. Will it be a problem if I get an access token through your package, and then use it to obtain additional information through spotify package? Or it's better to simply make a direct call to the Spotify API endpoint using the access token from your package?

**Comment by fotiDim** [comment]
Yes that was exactly my suggestion. It's up to you to decide if you want to use the Spotify package. If it is for a single call I guess it does not make sense as it will bring a lot of dependencies.

But definitely double check how you plan to support desktop platforms.

**Comment by fotiDim** [comment]
@volgin can we close this? As suggested it is better to tackle this over the web api.

**Comment by volgin** [comment]
Yes, you can close it.
