### ISSUE TITLE
Support spotify search API

### ISSUE THREAD

**Issue by saroad2** [brim-borium/spotify_sdk#174]
**Is your feature request related to a problem? Please describe.**
Right now *spotify sdk* can link to a spotify remote, get the currently played track and control its playback.
One think that it cannot do currently is to use the [search API](https://developer.spotify.com/console/get-search-item/) to look for items in Spotify. This is a very important ability for people that wants to use this library.

In my specific case, I need to be able to let my users search for a track in Spotify and save it in a database.

**Describe the solution you'd like**
One should be able to call search method via the sdk:
```dart
final result = await SpotifySdk.search(q="all the single ladies", type="track")
```

**Describe alternatives you've considered**
Not relevant.

**Additional context**
Not relevant.

**Comment by saroad2** [comment]
Hey @banool , thanks for the suggestion!

I actually started working on a PR for this. It seems like this repo is the main effort to have a fully functioning Spotify sdk for dart.

 @brim-borium Is this repo managed? or it's officially dead?
If it's not, maybe I can tackle this problem and maybe some more 😄

**Comment by banool** [comment]
I wouldn't say it's dead, I'd say people like you and I come along every so often and push it forward a bit 😛

**Comment by brim-borium** [comment]
@saroad2 hi thanks for the request :) I wouldn't say it's dead I just haven't had the time lately to work on it. I will have a look between the holidays and see if I can update some things. And if you get your PR ready I can also have a look at it.

**Comment by brim-borium** [comment]
Also another thing that I wanted to do is move the whole package to a federated architecture: https://docs.flutter.dev/development/packages-and-plugins/developing-packages#federated-plugins

Depending on the progress of your PR I will wait with this until you finished :)

**Comment by saroad2** [comment]
Hey, I really tried to tackle that issue without success.
I'm really new to dart and flutter so I still have a lot to learn.

If you'll manage to tackle this issue soon, I'll be glad. If not, that's totally OK :)

**Comment by brim-borium** [comment]
Hey @saroad2 I think I will then move first to the federated architecture and try to tackle this issue afterwards. In general this will be a bigger thing to do I think, because the intent of this package was to enable the auth and remote sdk's. If we start implementing the search api, this will probably lead to implementing the whole web api, and there are already packages that implement the web api (including search). https://pub.dev/packages/spotify

**Comment by fotiDim** [comment]
Why do we need the web api in this package? https://pub.dev/packages/spotify has this already and the 2 package play nice together. My opinion is that this is out of scope.

**Comment by brim-borium** [comment]
Agreed with @fotiDim Therefore this issue will be closed
