### ISSUE TITLE
getAccessToken failing

### ISSUE THREAD

**Issue by Sahilhawal** [brim-borium/spotify_sdk#177]
**Is this a how to question?**
No

**Is this a native Spotify SDK issue?**
No

**Have you searched for existing issues?**
Yes

**Are you using a Free or Premium Spotify account?**
Premium

**Are you aware of the limitations of Free Spotify accounts?**
Yes

**Expected behavior**
After calling the getAccessToken API, a token should be returned

**Describe the bug**
If the Spotify app is not installed on the device and if a "getAccessToken" API call is made then the auth token is received from the API 
but, if the Spotify  app is installed on the device and a "getAccessToken" API call is made following error gets thrown
 ⛔ getAccessToken failed with: Authentication went wrong
 ⛔ AUTHENTICATION_SERVICE_UNAVAILABLE

**Spotify_sdk Flutter package version**
2.3.0

**Target Platform, Version & Device**
 - OS & Version: [Android 13]
 - Browser & Version (if applicable) [e.g. Safari 15, Chrome 22]
 - Device: Pixel 6a
 
**Development OS**
 - OS: Mac OS

**Comment by wsdt** [comment]
Same issue here! Can confirm this.

**Comment by Jo-Chris** [comment]
Same error & reproduced it with app removal. Works fine if Spotify application is not installed.

**Comment by lorenzovianello-vivaldigroup** [comment]
Same issue!!
Did you solved something ?

**Comment by lorenzovianello-vivaldigroup** [comment]
@Sahilhawal 

Solution is basically ONE.
The only case in which Spotify won't let you use the app is when your application package name and SHA1 are not linked to Spotify's developer dashboard.
You can easilly retrieve package name via AndroidManifest (eg. com.example.application)
SHA1 is retrieved via android studio running 'gradle signingreport' via terminal in gradle folder

Then you add to your dashboard of Spotify the 2 data and its done.

Hope it helps

**Comment by Flajt** [comment]
It fails for me too and I think I got the correct package name and SHA1 (SHA1 extracted for debug certificate via: `keytool -alias androiddebugkey -keystore ~/.android/debug.keystore -list -v | grep SHA1`)

**Comment by brim-borium** [comment]
@wsdt @Jo-Chris  @Sahilhawal  does the proposed solution from @lorenzovianello-vivaldigroup worked for you?

**Comment by fotiDim** [comment]
> **Is this a native Spotify SDK issue?** No

This is clearly a native SDK issue. If you have searched a bit you would have come up with [this issue](https://github.com/spotify/android-sdk/issues/318). I suggest you follow it for any suggested solutions.

I have also come across this and just switching to a different client id solved the issue for me. In the majority of the cases (if not all) the error is the result of misconfiguration. Closing...
