### ISSUE TITLE
Too many logs: 'Unable to resolve ***'

### ISSUE THREAD

**Issue by lucavinci** [brim-borium/spotify_sdk#19]
**Describe the bug**
While running the app, my console is spammed with 
`Unable to resolve Lcom/spotify/protocol/types/PlayerContext; annotation class 1761`
logs. 
This makes it hard to read any logs from other app features.

**To Reproduce**
1. Run any app with this library
2. Look in the console/run-window of the app

**Expected behavior**
Suppress the logs

**Screenshots**
![screenshot](https://i.imgur.com/s911fYm.png)

**Desktop (please complete the following information):**
 - OS: OSX 
 - Browser: Chrome

**Smartphone (please complete the following information):**
 - Device: Galaxy S10, Android Emulator
 - OS: Android 10
 - Browser Chrome

**Additional context**
-

**Comment by brim-borium** [comment]
I'll have a look into this tomorrow :)

**Comment by brim-borium** [comment]
A quick look into this revealed that this seems to be an issue with the spotify sdk itself logging too much/not supressing some logs

**Comment by brim-borium** [comment]
I added the issue to the spotify sdk issue board, still looking for a way to suppress the logs, probably proguard can help here
https://github.com/spotify/android-sdk/issues/226

**Comment by lucavinci** [comment]
Thank you, should I leave this issue open?

**Comment by brim-borium** [comment]
Yeah, will close this, when this gets fixed

**Comment by fotiDim** [comment]
As the corresponding issue on the native Android SDK has been long standing there seems to be no guarantee that this will be resolved. We are closing this issue and suggest to follow the corresponding issue on the native Android SDK for updates.
