### ISSUE TITLE
Update Spotify SDK in time for Android 14

### ISSUE THREAD

**Issue by fotiDim** [brim-borium/spotify_sdk#195]
**Is your feature request related to a problem? Please describe.**
Spotify sent out an email today letting devs know about their newest Android SDK version which addresses the new Foreground Services changes in Android 14. More info [here](https://developer.spotify.com/blog/2023-07-06-new-android-sdk-version).

**Describe the solution you'd like**
We should update the Android SDK to the proposed version.

cc @brim-borium

**Comment by brim-borium** [comment]
Yeah I agree :) Do you want to tackle this or should I?

**Comment by fotiDim** [comment]
@brim-borium it will be a while until I have some time to work on it. Need to finish some other things first.

**Comment by brim-borium** [comment]
Ok I will give it a try this weekend :)
