### ISSUE TITLE
Multiple accounts

### ISSUE THREAD

**Issue by Narsku** [brim-borium/spotify_sdk#199]
Hi!, this library supports multi accounts?, i want to connect at least two spowify accounts to my app (not at the same time). Thanks in advance

**Comment by brim-borium** [comment]
Hi @Narsku This is currently not supported Because you can just authenticate with one account, due to limitations to the spotify sdk itself

**Comment by T1G3R192** [comment]
Hi @brim-borium, everything worked fine until I switched from a test spotify account to my personal account (free > premium). I could not connect to the remote API anymore. I even wiped the data of my emulator and reinstalled spotify. Nothing. Are you familiar with the problem?
