### ISSUE TITLE
MissingPluginException when running on iOS device

### ISSUE THREAD

**Issue by jackvdp** [brim-borium/spotify_sdk#20]
When running this app on an IOS device I receive the following error. What am I doing wrong?

════════ Exception caught by services library ══════════════════════════════════════════════════════
The following MissingPluginException was thrown while de-activating platform stream on channel connection_status_subscription:
MissingPluginException(No implementation found for method cancel on channel connection_status_subscription)

When the exception was thrown, this was the stack: 
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:154:7)
<asynchronous suspension>
#1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:329:12)
#2      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:531:29)
#3      EventChannel.receiveBroadcastStream.<anonymous closure> (package:flutter/src/services/platform_channel.dart:528:18)

**Comment by brim-borium** [comment]
Hi @jackvdp iOS is not implemented yet and further work on this is on hold at the moment, because I can't find the time to work on that.

**Comment by jackvdp** [comment]
Ah that's a shame. I saw that it's under construction for iOS, but was hoping I'd be able to get at least playback info at this point. Fingers crossed you get some time in the future to finish off - great work so far!

**Comment by brim-borium** [comment]
Closing this issue because this will be handled in #5
