### ISSUE TITLE
Error connecting to the service protocol: failed to connect to 

### ISSUE THREAD

**Issue by Naguchennai** [brim-borium/spotify_sdk#206]
After logged in 

  "Error connecting to the service protocol: failed to connect to http://127.0.0.1:63770/J2fhI7UdfOE=/"

**Comment by fotiDim** [comment]
@Naguchennai please fill in the issue template. Issues without the necessary info will be closed.

**Comment by brim-borium** [comment]
Issue will be closed due to inactivity
