### ISSUE TITLE
Crash when parsing the Spotify iOS SDK response after connecting

### ISSUE THREAD

**Issue by Kris9000** [brim-borium/spotify_sdk#209]
**Is this a how to question?**
No

**Is this a native Spotify SDK issue?**
I don't know

**Have you searched for existing issues?**
Yes

**Are you using a Free or Premium Spotify account?**
Free

**Are you aware of the limitations of Free Spotify accounts?**
Yes

**Expected behavior**
Spotify redirects to my app and playback starts.

**Describe the bug**
The app crashes after having logged the following messages:

`AppRemote: Connecting...
flutter: APP: Lifecycle state changed: AppLifecycleState.hidden
flutter: APP: Lifecycle state changed: AppLifecycleState.inactive
flutter: APP: Lifecycle state changed: AppLifecycleState.resumed
[connection] nw_socket_handle_socket_event [C1.1.1:1] Socket SO_ERROR [61: Connection refused]
AppRemote: Established a connection to the Spotify app.
AppRemote: Authenticated with the Spotify app.
AppRemote: Established a session with the Spotify app.
flutter: \^[[38;5;12mconnect to spotify successful<…>
flutter: SPOTIFY Player connection status: Instance of 'ConnectionStatus'
AppRemote: Requesting subscription: <SPTAppRemoteSubscription: 0x282ebe300; id: 0; topic: com.spotify.player_state>
AppRemote: Started subscription: <SPTAppRemoteSubscription: 0x282ebe300; id: 4; topic: com.spotify.player_state>
AppRemote: Received event: <SPTAppRemoteSubscriptionEvent: 0x2820a9e60; id: 1> for subscription: <SPTAppRemoteSubscription: 0x282ebe300; id: 4; topic: com.spotify.player_state>
playerStateDidChange
warning: spotify_sdk was compiled with optimization - stepping may behave oddly; variables may not be available.
* thread #1, queue = 'com.apple.main-thread', stop reason = Swift runtime failure: Index out of range
    frame #1: 0x00000001019cb70c spotify_sdk`specialized static State.playerContextDictionary(_:) [inlined] generic specialization <Swift.String> of Swift.Array._checkSubscript(_: Swift.Int, wasNativeTypeChecked: Swift.Bool) -> Swift._DependenceToken at <compiler-generated>:0 [opt]
Note: this address is compiler-generated code in function generic specialization <Swift.String> of Swift.Array._checkSubscript(_: Swift.Int, wasNativeTypeChecked: Swift.Bool) -> Swift._DependenceToken that has no source code associated with it.
Target 0: (Runner) stopped.
Lost connection to device.`

**Steps to Reproduce**
1. Call SpotifySDK.connectToSpotifyRemote()

**Screenshots**

**Spotify_sdk Flutter package version**
Check you `pubspeck.lock` file to verify the exact version [e.g 2.1, commit ID]

**Target Platform, Version & Device**
 - OS & Version: iOS 16.6.1
 - Device: iPhone 12 Mini
 
**Development OS**
 - MacOS 13.4.1

**Comment by fotiDim** [comment]
@Kris9000 which version of the library are you using?
Do you experience the crash with the example app after you configure your own credentials?

**Comment by fotiDim** [comment]
Closing as no feedback was submitted. We can reopen if the issue persists.
