### ISSUE TITLE
connectToSpotifyRemote() Not working

### ISSUE THREAD

**Issue by tkddbf7348** [brim-borium/spotify_sdk#214]
Hi, I'm using version Spotify_sdk 2.3.1 on Flutter 3.19.0.

I set it up using the spotify-app-remote-release-0.8.0.aar file and there is no problem building the app.

However, if you use the SpotifySdk.connectToSpotifyRemote function after building the app, an error occurs inside the function, and the function cannot be executed and the function is terminated.

Spotify is installed on device and using a premium account.

Redirect URI, Android Packages, etc. have been set up in the Spotify developer console.

Is there a way to solve it? I would appreciate it if you could leave a reply after reading it.

We tested it with the Galaxy S21 (Android 14) in a Windows environment.

![image](https://github.com/brim-borium/spotify_sdk/assets/46470539/5ae35d3e-8aee-46c5-ac11-b18ddcff4437)

Nothing other than that log is displayed.

**Comment by iampawan** [comment]
@tkddbf7348 are you aware about what is this exact issue?

**Comment by tkddbf7348** [comment]
@iampawan  No, my problem was caused by my mistake and currently works fine on my app!

I had a problem with setting the redirection url incorrectly on Spotify.

**Comment by iampawan** [comment]
@tkddbf7348 How are you setting the redirect url? Can we provide a url scheme like iOS which can just open the app itself rather than having a https url? Can you help with that?

**Comment by tkddbf7348** [comment]
@iampawan

In my case, I set it up like 'example-player://callback'.
Register the name before '://' with BundleURLScheme in Info.plist.
If you set it like that and then set Apple Bundle Id, Android Package name, and SHA1 fingerprint, it will work normally.

Details are explained in the Spotify SDK's guide, so please refer to it and develop it. 
Please understand that I am not very good at it, so I can't tell you much.

**Comment by iampawan** [comment]
Thanks, I followed the same and it's working fine for iOS but not for Android. How did you setup the urlscheme on Android?
