### ISSUE TITLE
Forcing premature update to android SDK 35

### ISSUE THREAD

**Issue by Jon-Salmon** [brim-borium/spotify_sdk#225]
**Is this a how to question?**
No

**Is this a native Spotify SDK issue?**
No

**Have you searched for existing issues?**
Yes

**Are you using a Free or Premium Spotify account?**
N/A

**Are you aware of the limitations of Free Spotify accounts?**
Yes

**Expected behavior**
I should be able to compile my app with this plugin, without updating the android SDK version of my app to 35.

**Describe the bug**
After updating to the latest version of this plugin, I am unable to compile my app while targeting android SDK version 34. While I agree that the end developer should update the target SDK version of their app in time, this should not be forced by a plugin. The official guidance on how to update android SDK verisons does not push for immidiate update once the new SDK is formally released (https://developer.android.com/about/versions/15/migration).

Here is an example of a similar issue from the last android SDK release cycle: https://github.com/fluttercommunity/plus_plugins/pull/2228

**Steps to Reproduce**
1. Create a new flutter app
2. Add this package
3. Attempt to compile for android

**Spotify_sdk Flutter package version**
3.0.1

**Target Platform, Version & Device**
 - OS & Version: Android
 - Device: Any android device
 
**Development OS**
 - OS: Windows

**Comment by brim-borium** [comment]
Hi @Jon-Salmon, I will revert this in #224

**Comment by Jon-Salmon** [comment]
Thanks!
