### ISSUE TITLE
MissingPluginException(No implementation found for method getAuthenticationToken on channel spotify_sdk)

### ISSUE THREAD

**Issue by ollydixon** [brim-borium/spotify_sdk#36]
flutter: \^[[38;5;12m┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>
flutter: \^[[38;5;12m│ #0   SpotifySdk._logException (package:spotify_sdk/spotify_sdk.dart:493:1<…>
flutter: \^[[38;5;12m│ #1   SpotifySdk.getAuthenticationToken (package:spotify_sdk/spotify_sdk.dart:119:<…>
flutter: \^[[38;5;12m├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄<…>
flutter: \^[[38;5;12m│ 💡 getAuthenticationToken not implemented<…>
flutter: \^[[38;5;12m└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────<…>
flutter: unable to init spotify
flutter: MissingPluginException(No implementation found for method getAuthenticationToken on channel spotify_sdk)

**Comment by fotiDim** [comment]
@ollydixon would be nice to mention on which platform you are getting this.

**Comment by ollydixon** [comment]
@fotiDim thanks for the quick reply. iOS.
Flutter (Channel unknown, v1.17.5, on Mac OS X 10.15.6 19G73, locale en-NO)

**Comment by fotiDim** [comment]
There are open PRs for iOS. Once merged this will be an non-issue. Closing.

**Comment by ollydixon** [comment]
@fotiDim ah so it's a known issue, surely the issue should remain open until the PR is merged and tested? (standard procedure)

**Comment by ollydixon** [comment]
@fotiDim It doesn't look like the PR's a fix for the library?

**Comment by fotiDim** [comment]
> @fotiDim ah so it's a known issue, surely the issue should remain open until the PR is merged and tested? (standard procedure)

The readme now indicates that it is not implemented, so it is already documented. We can't have an issue for every not implemented feature.
If you want to test it out you can checkout the branch of the PR and provide your feedback there. Better to have the conversation in a single place.

> @fotiDim It doesn't look like the PR's a fix for the library?

Not sure what you mean. I am talking about [this PR](https://github.com/brim-borium/spotify_sdk/pull/3)

**Comment by ollydixon** [comment]
@fotiDim ah we spend all morning trying to fix it :-/ thanks for putting it on the README though for future users.

**Comment by ollydixon** [comment]
@fotiDim we tried implement the framework and it's still broken, same error message. Also, where do we place the framework? Inside Runner? It's not specific at all. 👎

**Comment by fotiDim** [comment]
Giving thumbs down to people working for free is not really helping. If you find something missing in the documentation then go ahead and make a PR to fix it. This is a community project.

If you have issues on where to place the iOS Spotify framework please open another issue. It has nothing to do with `getAuthenticationToken`.

I suggest that you read the readme carefully and then try to run the example app. If it is all confusing to you better wait for the PR to be merged.

**Comment by brim-borium** [comment]
Just for clarification, this package at the current state does not support iOS. There is a PR indicating that we are working on the iOS implemention. All of this is in the readme on pub.dev. the readme here indicates the current state of development not the current state of the released package

**Comment by ollydixon** [comment]
@fotiDim @brim-borium there was no mention of the lack of iOS support on both GitHub and Pub.Dev, instead we had to waste our time trying to use this library. You need handle criticism in development to grow and become more aware of issues like this; it's all fine and dandy that you're making this framework; and I appreciate that just be aware that a lot of folks use Flutter professionally and we lose hundreds of dollars for simple things like this, you cost me more than $600 by not specifying there was no support.

**Comment by brim-borium** [comment]
By providing this package we probably saved you a lot of money if it would fit your needs. An talking about criticism. There a actually a lot of signs that iOS is not supported at the moment.

First evidence iOS is not mentioned in the supported platforms.

![Screenshot_20200903-163229.jpg](https://user-images.githubusercontent.com/4504079/92128875-2453b680-ee03-11ea-8fcc-f3c889b1500e.jpg)

Second evidence, there is no instructions for iOS. 

Third evidence, the API description at the bottom of the page clearly states that iOS is in construction. Every single column is marked in construction for iOS.

Claiming to be a professional, but clearly not reading the package instructions suggests otherwise.

And yes, we could put it in big red letters on top of the page. But we thought that this would be enough.

**Comment by ollydixon** [comment]
@brim-borium why on earth would you create a flutter plugin for Android only? If you ever see any plugin that does not support iOS and only Android? They usual label that in big text at the start of the README because no one looks at those tags; they assume it is supported.

"Second evidence, there is no instructions for iOS.", are you new to Flutter? Most packages have no iOS install instructions. In fact, this package could be constructed without install steps making it easier for the developers and maintainers, right now the setup is very 'un-flutter' and has the markings of amateur plugin developers. Might be something worth looking into.

"page clearly states that iOS is in construction" those columns are not clear at all. It almost looked glitched, it has a massive tick left aligned then 'Android iOS' with the word ':construction_worker:' wtf does that mean? Maybe 'Under development' would have been a better choice..

At the rate of development on this package though I think it's going to be wiser to just create our own one in day anyhow; good luck with it all.
