### ISSUE TITLE
Universal redirect URLs not working

### ISSUE THREAD

**Issue by fotiDim** [brim-borium/spotify_sdk#48]
If the redirect URL is set to be an HTTP(S) URL then the `open url:` callback on iOS is never called and the connection never completes. It does work when the URL uses a custom scheme (e.g. my-app://sth). Not sure if Flutter even supports informing plugins for handling universal URLs.

**Comment by fotiDim** [comment]
Figured it out. Will be resolved soon.

**Comment by fotiDim** [comment]
Done

**Comment by ollydixon** [comment]
@fotiDim how does this work then? What is the format of the redirect url?
