### ISSUE TITLE
iOS support

### ISSUE THREAD

**Issue by itsMatoosh** [brim-borium/spotify_sdk#5]
Hi, this is a great plugin! I was wondering when you're planning to add iOS support. I am building an app which uses Spotify and I wanted to use this plugin. Also please let me know if you need any help in implementing the iOS side.

**Comment by brim-borium** [comment]
Hi Mateusz,

we are currently working on this, but this won't be finished until the end of January because of Holidays :) But if we have any updates in that I'll post it here

**Comment by trezm** [comment]
Keeping an eye on this as well, let me know if you want a hand, as this would be really useful for a project I'm working on!

**Comment by brim-borium** [comment]
You can talk to @Steffenberg he is currently working on the iOS implementation

**Comment by brim-borium** [comment]
@itsMatoosh @trezm I can add you as collaborators if you want and you can give it a try or continue working on @Steffenberg branch

**Comment by trezm** [comment]
I can take a look at that branch -- what's the current state of it? It looks like the description is blank

**Comment by brim-borium** [comment]
As far as I know the current state is that he managed to integrate the spotify sdk into the native project and now the sdk calls have to be implemented

**Comment by trezm** [comment]
:+1: sounds good

**Comment by lucavinci** [comment]
Awesome!

**Comment by brim-borium** [comment]
Update on this:
Currently we don't find the time working on the iOS integration. If somebody wants to have a look at it feel free to text me

**Comment by trezm** [comment]
I'm hoping to have some time this weekend to potentially work on this, no promises though!

**Comment by lucavinci** [comment]
I will also take a look at this in the evening, but unfortunately I do not have prior experience with swift or iOS development.

**Comment by lucavinci** [comment]
Any updates?

**Comment by brim-borium** [comment]
Not from my side. Got my hands full atm because of the Corona crisis :)

**Comment by trezm** [comment]
I actually began working on this in earnest last night. I'll have an update
and PR in the next few days.

**Comment by lucavinci** [comment]
Awesome, thanks for your work guys. I would love to help, but unfortunately I do not have any swift / objective c skills

**Comment by olmedocr** [comment]
I'm currently developing an app with flutter and I have some experience with swift and the Spotify SDK, so I'll try to contribute to this if I can, instead of using platform channels.

**Comment by trezm** [comment]
I tried to get this working on and off for about a month now, and I can't seem to get the spotify framework headers to properly package in a flutter package. I'm going to quit working on it for now as clearly I don't have the expertise required for this and am just spinning my wheels. Sorry all!

**Comment by helipin14** [comment]
any updates for this issue?

**Comment by lucavinci** [comment]
Spotify just opened their developer forum and I created a [thread](https://community.spotify.com/t5/Spotify-for-Developers/Flutter-support/m-p/4950620#M106) about it. I doubt they will help, but I think it would help if everyone here that also wants them to help, maybe likes the thread and/or comments on it to show that many people want this

**Comment by brim-borium** [comment]
The link doesn't seem to work :)

**Comment by brim-borium** [comment]
> any updates for this issue?

Sorry not right now. I will have a lot of time in a week for a month and will probably have a look at this issue again
