### ISSUE TITLE
SpotifySdk.getAuthenticationToken the code isn't valid for anything?

### ISSUE THREAD

**Issue by ollydixon** [brim-borium/spotify_sdk#55]
Currently the ```SpotifySdk.getAuthenticationToken``` returns a code that can't be used since we can't send properties like ```code_challenge``` as required for Code Exchange (PKCE) (https://developer.spotify.com/documentation/general/guides/authorization-guide/)

I tried to get a refresh token with it and it always failed, example node code

```
 const response = await Axios.post(
            'https://accounts.spotify.com/api/token',
            Querystring.stringify({
                grant_type: 'authorization_code',
                code: code, // SpotifySdk.getAuthenticationToken
                redirect_uri: redirectUri,
            }),
            {
                headers: {
                    'Authorization': 'Basic ' + new Buffer(`${Config.spotifyClientId}:${Config.spotifyClientSecret}`).toString('base64'),
                    'Content-Type': 'application/x-www-form-urlencoded',
                },
            }
        );
```

**Comment by fotiDim** [comment]
`getAuthenticationToken()` returns an `access token` not an `authorization code`. You cannot use that token for initiating login flows. There is also no way to get a refresh token from the native Android SDK and consequently not from this SDK. For potential updates follow [this](https://github.com/spotify/android-sdk/issues/255) and [this](https://github.com/spotify/android-sdk/issues/12) issue.

**Comment by ollydixon** [comment]
@fotiDim thanks for the reply. Are you saying that the web login is the only way to get a refresh token?

**Comment by fotiDim** [comment]
The native iOS and Android SDKs do not expose the refresh token. You can only get a refresh token by implementing `Authorization Code` flow or `Authorization Code With PKCE` flow but this is totally independent of this SDK.
