### ISSUE TITLE
spotify-app-remote-release-0.7.1.aar not supported

### ISSUE THREAD

**Issue by dormunis** [brim-borium/spotify_sdk#56]
**Describe the bug**
When using `spotify-app-remote-release-0.7.1.aar` release of spotify's android sdk, you get a LoggedOutException when trying to build gradle
Just thought you might wanna know

**To Reproduce**
1. Download the latest spotify-app-remote-release-0.7.1.aar from spotify sdk
2. Build
3. See error (LoggedOutException) which is not mapped in your exception in SpotifySdkPlugin.kt

**To Solve**
Just download `spotify-app-remote-release-0.7.0.aar` which is the previous release and it works.

maybe I'll create a PR with a fix, but for now, this is a quick win

**Comment by brim-borium** [comment]
Hi @dormunis thanks for creating the issue. I just had a quick lock into the release changes for 0.7.1

> What's new?
Replaced LoggedOutException usages with NotLoggedInException and removed LoggedOutException completely.
Introduced VolumeState class and added volume control to ConnectApi.

LoggedOutException has been removed completely so we have to change that in the package. I will probably change this during this week

**Comment by brim-borium** [comment]
@dormunis a new version of the package has been published, please check if you still have the same issues regarding spotify-app-remote-release-0.7.1

**Comment by fotiDim** [comment]
Closing because of lack of feedback. If it is still an issue please comment back and we will reopen it.
