### ISSUE TITLE
Play song with custom notification

### ISSUE THREAD

**Issue by skyberk** [brim-borium/spotify_sdk#63]
SpotifySdk.play working perfectly but i dont want to use spotify's default sticky notification. Can i hide it or create a custom notification for my app when user play song. Because user shouldnt skip the music in my app scenario.

**Comment by brim-borium** [comment]
Hi @skyberk I did't find a way to do this when the spotify app is installed on your device. It probably would work if you don't have the spotify app installed on your device, but I am not sure right now if the current authentication flow would work then. If you can check out wether it works if the spotify app is not installed on your device

**Comment by skyberk** [comment]
Hi @brim-borium thanks for responding. Actually i saw working example on Musixmatch application. It has custom sticky notification even spotify app exists. I think they are using web api flow on mobile devices but it may not be legit by Spotify. 

https://play.google.com/store/apps/details?id=com.musixmatch.android.lyrify

**Comment by fotiDim** [comment]
Closing this. Feel free to reopen there is a way to implement this as requested.
