### ISSUE TITLE
Spotify Interaction

### ISSUE THREAD

**Issue by Guennx** [brim-borium/spotify_sdk#64]
**Describe the bug**
Example codes can't interact with spotify.
(Spotify is installed on the device)

**To Reproduce**
1. Click on 'get auth token' button
2. Sign in
3. See [error])

**Desktop:**
 - OS: Windows 10 
 - Build gradle version: 3.5.4    

**Smartphone:**
 - Device: Xiaomi Mi Mix 2
 - OS: Android 9

**Additional context**
Also connectToSpotifyRemote method doesn't work.

**Error:** 🐛 CouldNotFindSpotifyApp : The Spotify app is not installed on the device

**Screenshots:**
![Screenshot_2020-10-31-20-17-30-002_de minimalme spotify_sdk_example](https://user-images.githubusercontent.com/61318808/97785562-d36bfe80-1bb6-11eb-9441-8e522e4a376a.jpg)
![Ekran Alıntısı](https://user-images.githubusercontent.com/61318808/97785578-e088ed80-1bb6-11eb-8c4c-91b0ae2e3053.PNG)

**Comment by fotiDim** [comment]
Did you try to setup your own client id and redirect url?

**Comment by Guennx** [comment]
Yes I tried but I'm not sure of my url

Redirect url: "https://accounts.spotify.com/authorize"

**Comment by fotiDim** [comment]
@Guennx that is definitely wrong. Follow the guide [here](https://developer.spotify.com/documentation/android/quick-start/)

**Comment by Guennx** [comment]
I got auth token by changing my redirect url but I'm still getting "🐛 CouldNotFindSpotifyApp : The Spotify app is not installed on the device" error.

**Comment by brim-borium** [comment]
So I tried this with the current master checked out and it worked on my side.

Quick question:
For the example code to work you have to add your client id and redirect url from the app the you created on https://developer.spotify.com/dashboard/applications. I guess you already did that. 

In this app you created in the spotify dashboard, did you add the Android package and sha1 as shown in the video?

![spotify_dashboard](https://user-images.githubusercontent.com/4504079/97811865-a3d3f980-1c7d-11eb-97e2-91f050a40393.gif)

If not you have to add the package displayed in the video and create a local sha1 on your local machine like in the second video
package: de.minimalme.spotify_sdk_example 

![create_local_sha1](https://user-images.githubusercontent.com/4504079/97811884-c1a15e80-1c7d-11eb-868c-31c40ee5c71a.gif)

**Comment by Guennx** [comment]
Thanks for replying,

I found that the problem was caused by me using a different spotify version, the api works great but I guess it doesn't support all of the spotify methods below. Do you plan to publish a new update on these methods?


![Ekran Alıntısı2](https://user-images.githubusercontent.com/61318808/98035852-2bf70200-1e2a-11eb-998d-bebd3feb846a.PNG)

**Comment by fotiDim** [comment]
@Guennx can you elaborate on `different spotify version`?

The image you posted shows categories of API endpoints. Most of them are already supported, see the readme file for more. Is there anything specific that you are missing?

**Comment by Guennx** [comment]
I was using "spotify premium apk" on my test device (unofficial version). I didn't think the problem was caused by this.

I want to search music and playlist, is this possible?

**Comment by fotiDim** [comment]
For searching you need to use with the Spotify Web API. It has nothing to do with the "Remote SDK". Having said that, you can use the access token you are getting from this library and use it on the web API calls, so you don't have to care about authentication.
This [plugin](https://pub.dev/packages/spotify) might help you with the API calls. Otherwise you have to implement them yourself which is not that complicated.
