### ISSUE TITLE
getAuthenticationToken()'s "scope" parameter is ignored on iOS.

### ISSUE THREAD

**Issue by ndahlquist** [brim-borium/spotify_sdk#69]
**Describe the bug**

**To Reproduce**

Request an auth token with a scope parameter, like so:

```dart
var scope = "app-remote-control,user-modify-playback-state,user-read-playback-state";
_authenticationToken = await SpotifySdk.getAuthenticationToken(
          clientId: _CLIENT_ID, redirectUrl: _REDIRECT_URL, scope: scope);
```

**Expected behavior**
I expect the Spotify client to open, and the user to be presented with the option to grant the Spotify app the requested scopes.

- On Android, this behavior works correctly, and all three scopes are requested:

![Screenshot_20210203-220707](https://user-images.githubusercontent.com/1558385/106852071-48dee380-666c-11eb-89dd-7d65951b6216.png)

- On iOS, the scope parameter is ignored, and only 2 scopes are requested:

![Screenshot 2021-02-03 at 10 06 26 PM](https://user-images.githubusercontent.com/1558385/106852124-66ac4880-666c-11eb-88ca-19b7ab36fab9.png)

**Smartphone (please complete the following information):**
 - Device: iPhone5, Pixel 4a
 - Version 1.0.0

**Additional context**

It looks like this is implemented in Android [here](https://github.com/brim-borium/spotify_sdk/blob/e69ff8f39fac4d0a571f27b72315a1cfe4314605/android/src/main/kotlin/de/minimalme/spotify_sdk/SpotifySdkPlugin.kt#L261), but [missing](https://github.com/brim-borium/spotify_sdk/blob/8f9661863b635ed6cbdc8aed8a5e0833f0e2802e/ios/Classes/SwiftSpotifySdkPlugin.swift#L71) in iOS.

I think this is also missing in the web version, but haven't tried that.

**Comment by fotiDim** [comment]
It is fixed now thanks to @nishiths23. You can point now your pubspec to latest version from master or wait for the next release.

**Comment by ndahlquist** [comment]
Thank you @nishiths23 @fotiDim!! 🤗
