### ISSUE TITLE
Can I get refresh_token??

### ISSUE THREAD

**Issue by mattun** [brim-borium/spotify_sdk#75]
I checked the source. It seems spotify_sdk_web.dart has a method to get refresh_token.
But spotify_sdk.dart doesn't have??

Thanks.

**Comment by fotiDim** [comment]
There is no way to get a refresh token from the native Android SDK and consequently not from this SDK.

**Comment by mattun** [comment]
Thanks ,I see. I wanna try to get refresh token throw web api.
