### ISSUE TITLE
web: error in application startup

### ISSUE THREAD

**Issue by gioboa** [brim-borium/spotify_sdk#80]
Hi everyone 👍 
I created an application and I followed the [getting started example](https://pub.dev/packages/spotify_sdk/example)

In android works like a charm. 😄 
If I run application with "flutter run -d chrome" and in console and in console I find this error:
```
spotify-player.js:23 Uncaught TypeError: tslib_1.__extends is not a function
    at spotify-player.js:23
    at Object.10.tslib (spotify-player.js:23)
    at o (spotify-player.js:2)
    at spotify-player.js:2
    at Object.11.../enums/errors (spotify-player.js:25)
    at o (spotify-player.js:2)
    at r (spotify-player.js:2)
    at spotify-player.js:2
```

**To Reproduce**
1. create new project
2. copy paste the example in main file
3. add correct spotify tokens
4. run application with "flutter run -d chrome"

I'm using flutter 2 stable.

I can share the repo if needed
Thanks

**Comment by brim-borium** [comment]
@itsMatoosh could you have a look at this?

**Comment by erikd234** [comment]
I just ran into the same error after inserting the correct tokens and running it on Chrome.

**Comment by fotiDim** [comment]
Can you try `flutter run -d web-server`?

**Comment by gioboa** [comment]
Same error 
![error](https://user-images.githubusercontent.com/35845425/111752201-b00bcc80-8895-11eb-87f1-46d940a0afa4.png)
nothing in terminal
![terminal](https://user-images.githubusercontent.com/35845425/111752195-ada97280-8895-11eb-91af-8d819dd8a23a.png)

**Comment by fotiDim** [comment]
What about this warning you are getting that the app is not configured to build on the web?

**Comment by gioboa** [comment]
I've notice it right now, I will try to solve it and retry 👍

**Comment by fotiDim** [comment]
I will try to have a look within the week and report back. @itsMatoosh is the expert for this though.

**Comment by itsMatoosh** [comment]
I took a look at this issue and it seems to only happen when running in debug mode. I tried manually loading the tslib library through a <script> tag, but that doesn't seem to fix the issue. 
It seems that the Javascript code of the application run in debug mode is somehow conflicting with the spotify-player.js script loaded from Spotify.
Weirdly enough, I'm not experiencing this problem in a production application running Flutter 2 with this plugin on web.

**Comment by brim-borium** [comment]
@itsMatoosh @gioboa Is there anything we can do on our end then ? Or can this issue be closed?

**Comment by gioboa** [comment]
So the problem is only in debug mode?

**Comment by gioboa** [comment]
I close the issue 👍

**Comment by incvv** [comment]
I suggested a workaround for this in https://github.com/brim-borium/spotify_sdk/issues/100#issuecomment-922374687
